---
driver:
  name: dokken
  chef_version: 16
  volumes:
   - /home:/host-home

provisioner:
  name: dokken

transport:
  name: dokken

platforms:
- name: centos-7
  run_list: yum-epel::default
  driver:
    image: centos:7

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        install_dir:         /opt/ex1
        build_user:          kitchen
        build_user_group:    kitchen
        build_user_password: kitchen

