#!/bin/sh

set -e

cd /opt/resque/etc/workers/url_title
# redirect stderr to stdout 'cause
# svlog logs stdout only (passwd as stdin by svrun)
exec 2>&1
export QUEUE=url_title
exec /opt/resque/embedded/bin/chpst -P -U omniresq  -u omniresq \
       	/opt/resque/embedded/bin/rake resque:work

